[package]
name = "irc-client"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
irc = "1.1.0"
rustyline = "17.0.2"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["macros", "full"] }
toml = "0.9.11"
[profile.release]
opt-level = "z"
debug=false
lto = "fat"
codegen-units = 1
panic = "abort"
